# -*- coding: utf-8 -*-
"""Notebook_Evelyn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpZ7ZUmg9zA2FdGKoIA4fspNXYP4513v

# 1.Contextualização

Este trabalho foi desenvolvido pela aluna Evelyn Klein (Turma 2026/1 - V2) como Projeto Final da Unidade Curricular "Modelagem de Dados" do programa SCTEC/SENAI para fins de avaliação e conclusão do Módulo 1 do Curso "Visualização de Dados e Business Intelligence".

Inicialmente, os dados foram consultados em um banco de dados SQL por meio de duas queries, responsáveis por extrair informações sobre funcionários, salários, departamentos e localização geográfica.

Em seguida, os dados passaram por etapas de exploração, análise estatística e visualização gráfica para identificação de padrões e geração de insights apresentadas neste notebook.

# 2.Objetivos

O principal objetivo deste projeto foi realizar uma Análise Exploratória de Dados (EDA) utilizando informações de funcionários de uma empresa. Para isso, buscou-se:

- extrair dados de um banco SQL utilizando consultas (queries);
- importar e manipular os dados no Python;
- realizar análises estatísticas descritivas;
- identificar padrões na distribuição dos salários;
- comparar a remuneração entre departamentos e regiões;
- identificar possíveis valores atípicos (outliers);
- apresentar os resultados por meio de gráficos e tabelas.

# 3.Metodologia

## 3.1 Banco de Dados e Consultas SQL

Foram utilizadas duas consultas SQL sobre a base de dados de Recursos Humanos (HR).

### 3.1.1 Query 1

A primeira consulta retornou informações sobre funcionários, incluindo identificação, cargo, departamento e salário.

Foram selecionadas as colunas EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOB_TITLE e DEPARTMENT_NAME, permitindo analisar a distribuição salarial entre cargos e departamentos.

### 3.1.2 Query 2

A segunda consulta reuniu dados de localização, como cidade, país e região.

Foram selecionadas as colunas EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME e REGION_NAME, possibilitando análises comparativas entre diferentes regiões geográficas.

Ambas as queries foram construídas com LEFT JOIN, preservando os registros da tabela principal e permitindo relacionar os campos das tabelas auxiliares mesmo quando alguma informação não estivesse disponível.

As duas bases foram posteriormente integradas pela coluna EMPLOYEE_ID, o que possibilitou cruzar as informações salariais com os dados de localização.

Após a execução das consultas, os resultados foram exportados para arquivos CSV e enviados ao repositório do GitHub do projeto.

O código SQL completo das consultas encontra-se disponível no Apêndice A deste trabalho e também na pasta `sql` do repositório.

## 3.2 Importação das Bibliotecas

Nesta etapa são importadas as bibliotecas necessárias para a análise dos dados: Path para organizar os caminhos do projeto, pandas para ler e tratar os CSVs e matplotlib para gerar os gráficos. Também foi configurada a formatação dos números para facilitar a leitura dos resultados.
"""

from pathlib import Path

try:
    PROJECT_DIR = Path(__file__).resolve().parent.parent
except NameError:
    BASE_DIR = Path.cwd()
    if (BASE_DIR / "data").exists():
        PROJECT_DIR = BASE_DIR
    elif (BASE_DIR.parent / "data").exists():
        PROJECT_DIR = BASE_DIR.parent
    else:
        PROJECT_DIR = BASE_DIR

DATA_DIR = PROJECT_DIR / "data"
OUTPUT_DIR = PROJECT_DIR / "outputs" / "figures"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

import matplotlib
RUNNING_AS_SCRIPT = "__file__" in globals()
if RUNNING_AS_SCRIPT:
    matplotlib.use("Agg")

import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8-whitegrid")
pd.set_option("display.float_format", "{:,.2f}".format)

CSV_URLS = {
    "query_01.csv": "https://raw.githubusercontent.com/evelynkleinenf-cloud/projeto_final/main/data/query_01.csv",
    "query_02.csv": "https://raw.githubusercontent.com/evelynkleinenf-cloud/projeto_final/main/data/query_02.csv",
}

def format_currency(value):
    return f"R$ {value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def load_csv(file_name):
    local_path = DATA_DIR / file_name
    if local_path.exists():
        return pd.read_csv(local_path)
    return pd.read_csv(CSV_URLS[file_name])

"""## 3.3 Carregamento dos CSVs

Nesta etapa são carregados os arquivos CSV gerados a partir das consultas SQL realizadas no banco de dados FreeSQL.

Os dados serão armazenados em DataFrames para permitir a análise exploratória.

"""

df1 = load_csv("query_01.csv")
df2 = load_csv("query_02.csv")

"""# 4.Análise Exploratória de Dados (EDA)

## 4.1 Verificação inicial dos dados
Nesta etapa foi realizada uma inspeção inicial dos dados para verificar se os arquivos CSV foram carregados corretamente.
"""

df1.head()

"""A visualização das primeiras linhas do conjunto de dados confirma que a Query 1 foi importada corretamente.

O conjunto contém informações de identificação dos funcionários, salário, cargo e departamento, que serão utilizadas nas análises estatísticas realizadas ao longo do estudo.
"""

df2.head()

"""A visualização das primeiras linhas da Query 2 confirma que os dados também foram importados corretamente.

O segundo conjunto reúne informações sobre departamentos, cidades, países e regiões dos colaboradores, possibilitando análises relacionadas à distribuição geográfica dos funcionários.

## 4.2 Estrutura e Qualidade dos Dados
A função info() foi utilizada para verificar o tipo de cada coluna e a quantidade de registros presentes nos conjuntos de dados.
"""

df1.info()

"""A estrutura do conjunto de dados da Query 1 demonstra que os tipos das colunas são adequados para a análise.

O conjunto possui 107 registros e foi identificado apenas 1 valor ausente na coluna DEPARTMENT_NAME, não comprometendo a qualidade dos dados.
"""

df2.info()

"""A estrutura da Query 2 apresenta 106 registros, com todas as colunas preenchidas, sem valores ausentes.

Os tipos de dados são compatíveis com as análises propostas, permitindo comparações entre funcionários, departamentos e regiões.

## 4.3 Estatísticas Descritivas
A função describe() foi utilizada para obter medidas estatísticas como média, desvio padrão, valores mínimo e máximo, auxiliando na compreensão da distribuição dos dados.
"""

df1.describe()

"""As estatísticas descritivas mostram que o conjunto possui 107 registros.

A média salarial é de 6.461,83, enquanto a mediana é de 6.200,00, indicando uma distribuição relativamente equilibrada, mas com salários mais elevados influenciando a média.

O menor salário é de 2.100,00 e o maior é de 24.000,00, evidenciando uma ampla variação salarial entre os colaboradores.
"""

df2.describe(include="all")

"""Observa-se que o conjunto possui 106 registros, com predominância do departamento Shipping, da cidade South San Francisco, do país United States of America e da região Americas.

A distribuição geográfica mostra concentração em poucas localidades, especialmente nos Estados Unidos e no Reino Unido, o que reforça a utilidade da base para comparações por localização.

## 4.4 Verificação de valores ausentes
Foi realizada a verificação de valores ausentes utilizando isnull().sum().
"""

df1.isnull().sum()

df2.isnull().sum()

"""O conjunto df1 apresentou apenas 1 valor nulo na coluna DEPARTMENT_NAME, enquanto o df2 não apresentou valores ausentes.

Como a quantidade de dados faltantes é insignificante, não foi necessário realizar tratamento adicional.

A etapa de Análise Exploratória de Dados permitiu compreender a estrutura dos conjuntos de dados, verificar a qualidade das informações e confirmar que os dados estavam adequados para as análises propostas.

Após essa validação, é possível dar continuidade nas análises específicas.

# 5.Análise da Distribuição Salarial

## 5.1 Estatísticas dos salários

Nesta etapa são calculadas medidas estatísticas para compreender a distribuição dos salários dos colaboradores.
"""

print(f"Média: {format_currency(df1['SALARY'].mean())}")
print(f"Mediana: {format_currency(df1['SALARY'].median())}")
print(f"Mínimo: {format_currency(df1['SALARY'].min())}")
print(f"Máximo: {format_currency(df1['SALARY'].max())}")

"""O resultado mostra que a base tem salário médio de 6.461,83 e mediana de 6.200,00, indicando que a maioria dos salários está concentrada em valores próximos de 6 mil reais. Como a média ficou um pouco acima da mediana, isso sugere a presença de salários mais altos puxando o valor médio para cima. O menor salário é 2.100,00 e o maior é 24.000,00, mostrando que existe uma diferença bem grande entre os colaboradores e que a distribuição salarial é bem variada.

## 5.2 Histograma de salários
"""

plt.figure(figsize=(8,5))
mean_salary = df1["SALARY"].mean()
median_salary = df1["SALARY"].median()
ax = plt.gca()
ax.hist(df1["SALARY"], bins=12, edgecolor="white", color="#4C78A8", alpha=0.9)
ax.axvline(mean_salary, color="#E45756", linestyle="--", linewidth=2, label=f"Média: {format_currency(mean_salary)}")
ax.axvline(median_salary, color="#54A24B", linestyle="-.", linewidth=2, label=f"Mediana: {format_currency(median_salary)}")
ax.set_title("Distribuição dos salários")
ax.set_xlabel("Salário")
ax.set_ylabel("Quantidade de funcionários")
ax.legend()
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "histograma_salarios.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""O histograma mostra que a maior parte dos colaboradores está concentrada nas faixas salariais mais baixas e intermediárias.

A linha da média acima da mediana reforça a presença de salários altos que puxam a distribuição para a direita, embora a maior parte dos valores esteja concentrada abaixo de R$ 10.000,00.

## 5.3 Média salarial por departamento

A seguir é apresentada a média salarial dos colaboradores em cada departamento, permitindo identificar diferenças entre os setores da empresa.
"""

media_depto = (
    df1.groupby("DEPARTMENT_NAME")["SALARY"]
    .mean()
    .sort_values(ascending=True)
)

fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.barh(media_depto.index, media_depto.values, color="#4C78A8")

ax.set_title("Média Salarial por Departamento")
ax.set_xlabel("Salário médio")
ax.set_ylabel("Departamento")

for bar, value in zip(bars, media_depto.values):
    ax.text(
        bar.get_width() + 150,
        bar.get_y() + bar.get_height() / 2,
        format_currency(value),
        va="center",
        fontsize=9
    )

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "media_salarial_por_departamento.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""A média salarial por departamento evidencia diferenças claras entre os setores da empresa. O departamento Executive apresenta a maior remuneração média, enquanto Shipping possui a menor média salarial. O gráfico facilita a comparação entre os departamentos e mostra que a remuneração varia bastante conforme a área analisada.

## 5.4 Top 10 cargos com maior média salarial
"""

media_cargo = (
    df1.groupby("JOB_TITLE")["SALARY"]
       .mean()
       .sort_values(ascending=False)
       .head(10)
)

media_cargo_plot = media_cargo.sort_values()
fig, ax = plt.subplots(figsize=(9,5))
media_cargo_plot.plot(kind="barh", ax=ax, color="#F58518")
ax.set_title("Top 10 Cargos com Maior Média Salarial")
ax.set_xlabel("Salário Médio")
ax.set_ylabel("Cargo")
ax.bar_label(ax.containers[0], labels=[format_currency(v) for v in media_cargo_plot], padding=3, fontsize=8)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "top_10_cargos_maior_media_salarial.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""Esta análise permite identificar quais funções concentram as maiores remunerações médias.

No topo da lista aparecem cargos estratégicos e de gestão, como President, Administration Vice President, Marketing Manager, Sales Manager e Finance Manager.

Também é possível observar que outros cargos especializados, como Public Relations Representative, Sales Representative e Public Accountant, permanecem entre os maiores salários médios.

## 5.5 Boxplot do salário por departamento
"""

plt.figure(figsize=(12,6))
df1.boxplot(
    column="SALARY",
    by="DEPARTMENT_NAME",
    rot=90,
    grid=False,
    showmeans=True,
    meanprops={
        "marker": "o",
        "markerfacecolor": "#F58518",
        "markeredgecolor": "black",
        "markersize": 5,
    },
)
plt.title("Salário por Departamento")
plt.suptitle("")
plt.xlabel("Departamento")
plt.ylabel("Salário")
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "boxplot_salario_por_departamento.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""O boxplot permite visualizar a distribuição dos salários em cada departamento, destacando a mediana, a dispersão dos valores e possíveis outliers.

Observa-se que o departamento Executive possui os maiores salários, enquanto Shipping, Purchasing e Administration apresentam remunerações mais baixas.

A presença de pontos mais afastados em alguns setores mostra diferenças salariais internas e ajuda a contextualizar a variabilidade da base.

## 5.6 Top 10 cargos com menor média salarial
"""

cargos_menores = (
    df1.groupby("JOB_TITLE")["SALARY"]
    .mean()
    .sort_values(ascending=True)
    .head(10)
)

fig, ax = plt.subplots(figsize=(10,8))
cargos_menores.plot(kind="barh", ax=ax, color="#54A24B")
ax.set_title("Top 10 Cargos com Menor Média Salarial")
ax.set_xlabel("Salário Médio")
ax.set_ylabel("Cargo")
ax.bar_label(ax.containers[0], labels=[format_currency(v) for v in cargos_menores], padding=3, fontsize=8)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "top_10_cargos_menor_media_salarial.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""Esta análise complementa o ranking dos cargos com maior média salarial, destacando as funções com menores remunerações médias.

Observa-se que cargos mais operacionais e de apoio, como Purchasing Clerk, Stock Clerk, Shipping Clerk e Administration Assistant, aparecem entre os menores salários, indicando uma diferença clara entre funções estratégicas e funções operacionais.

# 6.Análise Geográfica

## 6.1 Integração dos Dados
"""

df = pd.merge(
    df1,
    df2[["EMPLOYEE_ID", "REGION_NAME"]],
    on="EMPLOYEE_ID",
    how="left"
)

df_regiao = df.dropna(subset=["REGION_NAME"]).copy()

"""Nesta etapa, os dois DataFrames são unidos pela coluna EMPLOYEE_ID para relacionar salário e região. Depois, ficam apenas os registros com informação de região para a análise.

## 6.2 Média salarial por região
"""

fig, ax = plt.subplots(figsize=(8,5))

df_regiao.boxplot(
    column="SALARY",
    by="REGION_NAME",
    grid=False,
    showmeans=True,
    meanprops={
        "marker": "o",
        "markerfacecolor": "#F58518",
        "markeredgecolor": "black",
        "markersize": 5,
    },
    ax=ax
)

plt.title("Salário por Região")
plt.suptitle("")
plt.xlabel("Região")
plt.ylabel("Salário")
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "boxplot_salario_por_regiao.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""O boxplot indica que a região Europe tem salários mais altos e mais concentrados, Americas apresenta maior dispersão e um valor muito alto fora do padrão."""

media_regiao = (
    df_regiao.groupby("REGION_NAME")["SALARY"]
    .mean()
    .sort_values()
)

fig, ax = plt.subplots(figsize=(7,4))
bars = ax.barh(media_regiao.index, media_regiao.values, color="#E45756")

ax.set_title("Média Salarial por Região")
ax.set_xlabel("Salário médio")
ax.set_ylabel("Região")

ax.bar_label(bars, labels=[format_currency(v) for v in media_regiao.values], padding=3)

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "media_salarial_por_regiao.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""Observa-se que a região Europe tem a maior média salarial, com 8.916,67, enquanto a região Americas apresenta média menor, de 5.191,66. Isso indica diferença de remuneração entre as regiões analisadas.

## 6.4 Quantidade de Funcionários por Região
"""

func_por_regiao = df_regiao["REGION_NAME"].value_counts().sort_values()
fig, ax = plt.subplots(figsize=(7,4))
func_por_regiao.plot(kind="barh", ax=ax, color="#4C78A8")
ax.set_title("Quantidade de Funcionários por Região")
ax.set_xlabel("Quantidade de Funcionários")
ax.set_ylabel("Região")
ax.bar_label(ax.containers[0], labels=[str(int(v)) for v in func_por_regiao], padding=3)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "quantidade_funcionarios_por_regiao.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""O gráfico mostra que, entre os 106 registros com informação geográfica disponível, a região Americas concentra a maior quantidade de funcionários, com 70 registros, enquanto a região Europe possui 36. Isso indica maior concentração de colaboradores nas Américas na base analisada.

# 7.Análises Adicionais

## 7.1 Média salarial x quantidade de funcionários por departamento

Esta análise compara a remuneração média com o número de funcionários em cada departamento. Ela ajuda a identificar setores com salários mais altos, mas pouca equipe, e setores com muitos colaboradores e remuneração mais baixa.
"""

resumo_departamento = (
    df1.groupby("DEPARTMENT_NAME")
       .agg(
           MEDIA_SALARIAL=("SALARY", "mean"),
           QTD_FUNCIONARIOS=("EMPLOYEE_ID", "count")
       )
       .sort_values("MEDIA_SALARIAL", ascending=True)
)

def format_brl(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 9), sharey=True)

ax1.barh(
    resumo_departamento.index,
    resumo_departamento["MEDIA_SALARIAL"],
    color="#4C78A8"
)
ax1.set_title("Média Salarial por Departamento")
ax1.set_xlabel("Salário médio")
ax1.set_ylabel("Departamento")
ax1.bar_label(
    ax1.containers[0],
    labels=[format_brl(v) for v in resumo_departamento["MEDIA_SALARIAL"]],
    padding=3,
    fontsize=8
)
ax1.grid(axis="x", linestyle="--", alpha=0.3)

ax2.barh(
    resumo_departamento.index,
    resumo_departamento["QTD_FUNCIONARIOS"],
    color="#72B7B2"
)
ax2.set_title("Quantidade de Funcionários por Departamento")
ax2.set_xlabel("Quantidade de funcionários")
ax2.set_ylabel("Departamento")
ax2.bar_label(
    ax2.containers[0],
    labels=[str(int(v)) for v in resumo_departamento["QTD_FUNCIONARIOS"]],
    padding=3,
    fontsize=8
)
ax2.grid(axis="x", linestyle="--", alpha=0.3)

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "media_salario_qtd_departamento.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""O departamento Executive possui a maior média salarial, enquanto Shipping apresenta a menor. Já em quantidade de funcionários, Shipping e Sales concentram mais colaboradores, mostrando que setores com mais pessoas nem sempre são os que pagam melhor.

## 7.2 Faixas Salariais
"""

faixas = pd.cut(
    df1["SALARY"],
    bins=[0, 4000, 7000, 10000, 25000],
    labels=[
        "Até R$ 4.000",
        "R$ 4.001 - 7.000",
        "R$ 7.001 - 10.000",
        "Acima de R$ 10.000"
    ],
    include_lowest=True
)

faixas_contagem = faixas.value_counts().sort_index()

fig, ax = plt.subplots(figsize=(8, 4))
faixas_contagem.plot(kind="bar", ax=ax, color="#B279A2")
ax.set_title("Distribuição dos Funcionários por Faixa Salarial")
ax.set_xlabel("Faixa Salarial")
ax.set_ylabel("Quantidade")
ax.bar_label(ax.containers[0], labels=[str(int(v)) for v in faixas_contagem], padding=3)

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "distribuicao_por_faixa_salarial.png", dpi=150, bbox_inches="tight")
if not RUNNING_AS_SCRIPT:
    plt.show()
plt.close()

"""A maior parte dos funcionários está concentrada nas faixas salariais mais baixas e intermediárias, enquanto poucos colaboradores aparecem nas faixas acima de R$ 10.000. Isso reforça a existência de poucos salários muito altos na base.

# 8.Identificação de Outliers

Esta etapa identifica quais funcionários possuem salários considerados fora do padrão estatístico por meio do método do Intervalo Interquartil (IQR).
"""

Q1 = df1["SALARY"].quantile(0.25)
Q3 = df1["SALARY"].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df1[
    (df1["SALARY"] < limite_inferior) |
    (df1["SALARY"] > limite_superior)
]

print(f"Q1: {format_currency(Q1)}")
print(f"Q3: {format_currency(Q3)}")
print(f"IQR: {format_currency(IQR)}")
print(f"Limite inferior: {format_currency(limite_inferior)}")
print(f"Limite superior: {format_currency(limite_superior)}")
outliers

"""Foi identificado 1 funcionário com salário acima do padrão estatístico do conjunto de dados, pertencente ao departamento Executive e ao cargo President. Esse valor é o único acima do limite superior calculado pelo método IQR, reforçando seu caráter de outlier.

# 9.Principais Insights

- O departamento Executive possui a maior remuneração média da empresa, indicando concentração de cargos estratégicos.


- Shipping é o departamento com menor média salarial e também um dos que possuem maior número de colaboradores.

- A região Europe apresentou média salarial superior à região Americas para os funcionários presentes na base analisada.

- Apenas um salário foi considerado outlier, indicando que a distribuição salarial é relativamente consistente.

# 10.Limitações da Análise

A análise foi realizada com base em duas consultas SQL extraídas do banco de dados HR. Algumas informações presentes na base original não foram utilizadas, pois não faziam parte do escopo do projeto.

Além disso, um funcionário da base salarial não possuía correspondência na base geográfica, motivo pelo qual a análise por região considerou 106 registros com localização preenchida.

# 11.Conclusão

A análise permitiu compreender a estrutura salarial dos colaboradores a partir de duas perspectivas principais: departamentos e regiões.

Os resultados mostraram que o departamento Executive concentra as maiores remunerações, enquanto Shipping apresenta a menor média salarial.

Também foi observado que a região Europe possui média salarial superior à região Americas, considerando os registros com informações geográficas disponíveis.

A EDA também revelou que a maior parte dos salários está concentrada em faixas mais baixas e intermediárias, enquanto poucos colaboradores possuem remunerações muito elevadas. Esse comportamento foi confirmado pela identificação de um outlier, pertencente ao departamento Executive, indicando um salário significativamente acima do padrão geral.

As queries foram essenciais para organizar os dados em duas bases complementares: uma voltada à análise salarial e outra à análise geográfica. A junção dessas bases permitiu ampliar a análise e gerar insights mais completos sobre a distribuição de salários na empresa.

# 12.Apêndice A - Consultas SQL Utilizadas

As consultas SQL abaixo foram utilizadas para extrair os dados do banco HR, posteriormente exportados em formato CSV para a realização da Análise Exploratória de Dados (EDA).

Encontram-se disponibilizados no repositório os arquivos `sql/consultas_sql.sql`, `data/query_01.csv`, `data/query_02.csv` e `src/analise_eda.py`, que compõem o material principal deste projeto.
"""

"""
# QUERY 1: Funcionários, cargos e departamentos
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    e.salary,
    j.job_title,
    d.department_name
FROM hr.employees e
LEFT JOIN hr.jobs j
    ON e.job_id = j.job_id
LEFT JOIN hr.departments d
    ON e.department_id = d.department_id
WHERE e.salary IS NOT NULL
ORDER BY e.salary DESC;
"""

"""
# QUERY 2: Funcionários, departamentos e localização
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    d.department_name,
    l.city,
    c.country_name,
    r.region_name
FROM hr.employees e
LEFT JOIN hr.departments d
    ON e.department_id = d.department_id
LEFT JOIN hr.locations l
    ON d.location_id = l.location_id
LEFT JOIN hr.countries c
    ON l.country_id = c.country_id
LEFT JOIN hr.regions r
    ON c.region_id = r.region_id
WHERE d.department_name IS NOT NULL
ORDER BY r.region_name, c.country_name, l.city;
"""
